-- Step 0: Drop all snowflake resources to reset demo (also required: delete records from skyflow table)
DROP TASK IF EXISTS SKYFLOW_PROCESS_PII_TASK;
DROP STREAM IF EXISTS SKYFLOW_PII_STREAM;
DROP FUNCTION IF EXISTS SKYFLOW_DETOKENIZE(VARCHAR);
DROP PROCEDURE IF EXISTS SKYFLOW_PROCESS_PII();
DROP PROCEDURE IF EXISTS SKYFLOW_TOKENIZE_TABLE(VARCHAR);
DROP PROCEDURE IF EXISTS GRANT_ROLES_TO_CURRENT_USER();
DROP ROLE IF EXISTS Admin;
DROP ROLE IF EXISTS Developer;
DROP TABLE IF EXISTS DOCTORS_DEMO;
DROP SECRET IF EXISTS SKYFLOW_VAULT_SECRET;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS SKYFLOW_EXTERNAL_ACCESS_INTEGRATION;
DROP NETWORK RULE IF EXISTS SKYFLOW_APIS_NETWORK_RULE;
DROP DATABASE IF EXISTS SKYFLOW_DEMO;
