USE DATABASE SKYFLOW_DEMO;
DROP ROLE IF EXISTS ROLE_AUDIT_ADMIN;
DROP ROLE IF EXISTS ROLE_DATA_ENGINEER;
DROP ROLE IF EXISTS ROLE_MARKETING;
DROP SECRET IF EXISTS SKYFLOW_VAULT_SECRET;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS SKYFLOW_EXTERNAL_ACCESS_INTEGRATION;
DROP NETWORK RULE IF EXISTS SKYFLOW_APIS_NETWORK_RULE;
DROP DATABASE IF EXISTS SKYFLOW_DEMO;